# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EALaunchHelper/Server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x45\x41LaunchHelper/Server.proto\x12\x10\x65\x61x.services.ipc\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x07Request\x12)\n\x0brequestData\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"6\n\x08Response\x12*\n\x0cresponseData\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"9\n\rStreamMessage\x12(\n\nstreamData\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"$\n\rBinaryMessage\x12\x13\n\x0bmessageData\x18\x01 \x01(\x0c\"\x1f\n\x10SubscriptionInfo\x12\x0b\n\x03url\x18\x01 \x01(\t\"I\n\x14GetSubscriptionsResp\x12\x31\n\x05infos\x18\x01 \x03(\x0b\x32\".eax.services.ipc.SubscriptionInfo2\xfe\x01\n\nGrpcServer\x12\x46\n\rCreateRequest\x12\x19.eax.services.ipc.Request\x1a\x1a.eax.services.ipc.Response\x12R\n\x10GetSubscriptions\x12\x16.google.protobuf.Empty\x1a&.eax.services.ipc.GetSubscriptionsResp\x12T\n\x0eSubscribeEvent\x12\x1f.eax.services.ipc.StreamMessage\x1a\x1f.eax.services.ipc.StreamMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EALaunchHelper.Server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=105
  _globals['_REQUEST']._serialized_end=157
  _globals['_RESPONSE']._serialized_start=159
  _globals['_RESPONSE']._serialized_end=213
  _globals['_STREAMMESSAGE']._serialized_start=215
  _globals['_STREAMMESSAGE']._serialized_end=272
  _globals['_BINARYMESSAGE']._serialized_start=274
  _globals['_BINARYMESSAGE']._serialized_end=310
  _globals['_SUBSCRIPTIONINFO']._serialized_start=312
  _globals['_SUBSCRIPTIONINFO']._serialized_end=343
  _globals['_GETSUBSCRIPTIONSRESP']._serialized_start=345
  _globals['_GETSUBSCRIPTIONSRESP']._serialized_end=418
  _globals['_GRPCSERVER']._serialized_start=421
  _globals['_GRPCSERVER']._serialized_end=675
# @@protoc_insertion_point(module_scope)
