# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EALaunchHelper/TestIntegration.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$EALaunchHelper/TestIntegration.proto\x12 eax.services.ipc.testIntegration\"3\n\x1aNotifyLaunchHelperErrorReq\x12\x15\n\rerrorStringId\x18\x01 \x01(\t\"\x1d\n\x1bNotifyLaunchHelperErrorRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EALaunchHelper.TestIntegration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYLAUNCHHELPERERRORREQ']._serialized_start=74
  _globals['_NOTIFYLAUNCHHELPERERRORREQ']._serialized_end=125
  _globals['_NOTIFYLAUNCHHELPERERRORRESP']._serialized_start=127
  _globals['_NOTIFYLAUNCHHELPERERRORRESP']._serialized_end=156
# @@protoc_insertion_point(module_scope)
