# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EADesktop/AchievementsCache.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!EADesktop/AchievementsCache.proto\x12\x0c\x65\x61x.protobuf\"#\n\x04Icon\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0c\n\x04path\x18\x02 \x01(\t\"\xeb\x01\n\x0b\x41\x63hievement\x12\r\n\x05setId\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05howTo\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x07 \x01(\t\x12\x15\n\rpointProgress\x18\x08 \x01(\x05\x12\x1b\n\x13totalPointsRequired\x18\t \x01(\x05\x12\x12\n\nawardCount\x18\n \x01(\x05\x12!\n\x05icons\x18\x0b \x03(\x0b\x32\x12.eax.protobuf.Icon\"p\n\x11\x41\x63hievementsCache\x12\x13\n\x0blastRefresh\x18\x01 \x01(\x04\x12/\n\x0c\x61\x63hievements\x18\x02 \x03(\x0b\x32\x19.eax.protobuf.Achievement\x12\x15\n\rschemaVersion\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EADesktop.AchievementsCache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ICON']._serialized_start=51
  _globals['_ICON']._serialized_end=86
  _globals['_ACHIEVEMENT']._serialized_start=89
  _globals['_ACHIEVEMENT']._serialized_end=324
  _globals['_ACHIEVEMENTSCACHE']._serialized_start=326
  _globals['_ACHIEVEMENTSCACHE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
