# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EADesktop/AchievementsQueue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!EADesktop/AchievementsQueue.proto\x12\x0c\x65\x61x.protobuf\"\xd6\x01\n\x16\x41\x63hievementGrantRecord\x12\x0f\n\x07offerId\x18\x01 \x01(\t\x12\x12\n\nsdkVersion\x18\x02 \x01(\t\x12\x11\n\tpersonaId\x18\x03 \x01(\t\x12\r\n\x05\x61ppId\x18\x04 \x01(\t\x12\r\n\x05setId\x18\x05 \x01(\t\x12\n\n\x02id\x18\x06 \x01(\t\x12\x0c\n\x04\x63ode\x18\x07 \x01(\t\x12\x10\n\x08progress\x18\x08 \x01(\x05\x12:\n\x11\x61\x63hievementStatus\x18\t \x01(\x0e\x32\x1f.eax.protobuf.AchievementStatus\"k\n\x16\x41\x63hievementsGrantQueue\x12:\n\x0c\x61\x63hievements\x18\x01 \x03(\x0b\x32$.eax.protobuf.AchievementGrantRecord\x12\x15\n\rschemaVersion\x18\x02 \x01(\r*V\n\x11\x41\x63hievementStatus\x12\x0b\n\x07Unknown\x10\x00\x12\x0c\n\x08Progress\x10\x01\x12\x17\n\x13PreviouslyCompleted\x10\x02\x12\r\n\tCompleted\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EADesktop.AchievementsQueue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACHIEVEMENTSTATUS']._serialized_start=377
  _globals['_ACHIEVEMENTSTATUS']._serialized_end=463
  _globals['_ACHIEVEMENTGRANTRECORD']._serialized_start=52
  _globals['_ACHIEVEMENTGRANTRECORD']._serialized_end=266
  _globals['_ACHIEVEMENTSGRANTQUEUE']._serialized_start=268
  _globals['_ACHIEVEMENTSGRANTQUEUE']._serialized_end=375
# @@protoc_insertion_point(module_scope)
