# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EAUpdater/ConfigCache.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x45\x41Updater/ConfigCache.proto\x12\x0c\x65\x61x.protobuf\"0\n\x12\x43onfigKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"l\n\x0eGeneralConfigs\x12\x13\n\x0blastRefresh\x18\x01 \x01(\x04\x12\x30\n\x06values\x18\x02 \x03(\x0b\x32 .eax.protobuf.ConfigKeyValuePair\x12\x13\n\x0b\x63onfigScope\x18\x03 \x01(\x04\"\x92\x01\n\x0b\x43onfigCache\x12\x32\n\x0c\x63loudConfigs\x18\x01 \x01(\x0b\x32\x1c.eax.protobuf.GeneralConfigs\x12\x34\n\x0estatsigConfigs\x18\x02 \x01(\x0b\x32\x1c.eax.protobuf.GeneralConfigs\x12\x19\n\x11serializerVersion\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EAUpdater.ConfigCache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONFIGKEYVALUEPAIR']._serialized_start=45
  _globals['_CONFIGKEYVALUEPAIR']._serialized_end=93
  _globals['_GENERALCONFIGS']._serialized_start=95
  _globals['_GENERALCONFIGS']._serialized_end=203
  _globals['_CONFIGCACHE']._serialized_start=206
  _globals['_CONFIGCACHE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
