# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from EAConnect_microsoft import ContentControlService_pb2 as EAConnect__microsoft_dot_ContentControlService__pb2


class ContentControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AccountLink = channel.unary_unary(
                '/eax.connect.ContentControlService/AccountLink',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.AccountLinkRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.AccountLinkReply.FromString,
                )
        self.Install = channel.unary_unary(
                '/eax.connect.ContentControlService/Install',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.InstallRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.InstallReply.FromString,
                )
        self.Uninstall = channel.unary_unary(
                '/eax.connect.ContentControlService/Uninstall',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.UninstallRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.UninstallReply.FromString,
                )
        self.PauseInstall = channel.unary_unary(
                '/eax.connect.ContentControlService/PauseInstall',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.PauseInstallRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.PauseInstallReply.FromString,
                )
        self.ResumeInstall = channel.unary_unary(
                '/eax.connect.ContentControlService/ResumeInstall',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.ResumeInstallRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.ResumeInstallReply.FromString,
                )
        self.CancelInstall = channel.unary_unary(
                '/eax.connect.ContentControlService/CancelInstall',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.CancelInstallRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.CancelInstallReply.FromString,
                )
        self.Launch = channel.unary_unary(
                '/eax.connect.ContentControlService/Launch',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.LaunchRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.LaunchReply.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/eax.connect.ContentControlService/GetStatus',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.GetStatusReply.FromString,
                )
        self.MonitorStatus = channel.unary_stream(
                '/eax.connect.ContentControlService/MonitorStatus',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.MonitorStatusRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.ContentStatus.FromString,
                )
        self.OpenDesktop = channel.unary_unary(
                '/eax.connect.ContentControlService/OpenDesktop',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.OpenDesktopRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.OpenDesktopReply.FromString,
                )
        self.NavigateProductDetails = channel.unary_unary(
                '/eax.connect.ContentControlService/NavigateProductDetails',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.NavigateProductDetailsRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.NavigateProductDetailsReply.FromString,
                )
        self.HangUp = channel.unary_unary(
                '/eax.connect.ContentControlService/HangUp',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.HangUpRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.HangUpReply.FromString,
                )
        self.Echo = channel.unary_unary(
                '/eax.connect.ContentControlService/Echo',
                request_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.EchoRequest.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.EchoReply.FromString,
                )


class ContentControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AccountLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Install(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Uninstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseInstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeInstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelInstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Launch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDesktop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NavigateProductDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HangUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AccountLink': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountLink,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.AccountLinkRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.AccountLinkReply.SerializeToString,
            ),
            'Install': grpc.unary_unary_rpc_method_handler(
                    servicer.Install,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.InstallRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.InstallReply.SerializeToString,
            ),
            'Uninstall': grpc.unary_unary_rpc_method_handler(
                    servicer.Uninstall,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.UninstallRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.UninstallReply.SerializeToString,
            ),
            'PauseInstall': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseInstall,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.PauseInstallRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.PauseInstallReply.SerializeToString,
            ),
            'ResumeInstall': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeInstall,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.ResumeInstallRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.ResumeInstallReply.SerializeToString,
            ),
            'CancelInstall': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelInstall,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.CancelInstallRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.CancelInstallReply.SerializeToString,
            ),
            'Launch': grpc.unary_unary_rpc_method_handler(
                    servicer.Launch,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.LaunchRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.LaunchReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.GetStatusRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.GetStatusReply.SerializeToString,
            ),
            'MonitorStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorStatus,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.MonitorStatusRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.ContentStatus.SerializeToString,
            ),
            'OpenDesktop': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDesktop,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.OpenDesktopRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.OpenDesktopReply.SerializeToString,
            ),
            'NavigateProductDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.NavigateProductDetails,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.NavigateProductDetailsRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.NavigateProductDetailsReply.SerializeToString,
            ),
            'HangUp': grpc.unary_unary_rpc_method_handler(
                    servicer.HangUp,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.HangUpRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.HangUpReply.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=EAConnect__microsoft_dot_ContentControlService__pb2.EchoRequest.FromString,
                    response_serializer=EAConnect__microsoft_dot_ContentControlService__pb2.EchoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eax.connect.ContentControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContentControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AccountLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/AccountLink',
            EAConnect__microsoft_dot_ContentControlService__pb2.AccountLinkRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.AccountLinkReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Install(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/Install',
            EAConnect__microsoft_dot_ContentControlService__pb2.InstallRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.InstallReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Uninstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/Uninstall',
            EAConnect__microsoft_dot_ContentControlService__pb2.UninstallRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.UninstallReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PauseInstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/PauseInstall',
            EAConnect__microsoft_dot_ContentControlService__pb2.PauseInstallRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.PauseInstallReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResumeInstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/ResumeInstall',
            EAConnect__microsoft_dot_ContentControlService__pb2.ResumeInstallRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.ResumeInstallReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelInstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/CancelInstall',
            EAConnect__microsoft_dot_ContentControlService__pb2.CancelInstallRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.CancelInstallReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Launch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/Launch',
            EAConnect__microsoft_dot_ContentControlService__pb2.LaunchRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.LaunchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/GetStatus',
            EAConnect__microsoft_dot_ContentControlService__pb2.GetStatusRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.GetStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MonitorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/eax.connect.ContentControlService/MonitorStatus',
            EAConnect__microsoft_dot_ContentControlService__pb2.MonitorStatusRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.ContentStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenDesktop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/OpenDesktop',
            EAConnect__microsoft_dot_ContentControlService__pb2.OpenDesktopRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.OpenDesktopReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NavigateProductDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/NavigateProductDetails',
            EAConnect__microsoft_dot_ContentControlService__pb2.NavigateProductDetailsRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.NavigateProductDetailsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HangUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/HangUp',
            EAConnect__microsoft_dot_ContentControlService__pb2.HangUpRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.HangUpReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.connect.ContentControlService/Echo',
            EAConnect__microsoft_dot_ContentControlService__pb2.EchoRequest.SerializeToString,
            EAConnect__microsoft_dot_ContentControlService__pb2.EchoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
