# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from EAConnect_microsoft import Server_pb2 as EAConnect__microsoft_dot_Server__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GrpcServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRequest = channel.unary_unary(
                '/eax.services.ipc.GrpcServer/CreateRequest',
                request_serializer=EAConnect__microsoft_dot_Server__pb2.Request.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_Server__pb2.Response.FromString,
                )
        self.GetSubscriptions = channel.unary_unary(
                '/eax.services.ipc.GrpcServer/GetSubscriptions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_Server__pb2.GetSubscriptionsResp.FromString,
                )
        self.SubscribeEvent = channel.unary_stream(
                '/eax.services.ipc.GrpcServer/SubscribeEvent',
                request_serializer=EAConnect__microsoft_dot_Server__pb2.StreamMessage.SerializeToString,
                response_deserializer=EAConnect__microsoft_dot_Server__pb2.StreamMessage.FromString,
                )


class GrpcServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubscriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRequest,
                    request_deserializer=EAConnect__microsoft_dot_Server__pb2.Request.FromString,
                    response_serializer=EAConnect__microsoft_dot_Server__pb2.Response.SerializeToString,
            ),
            'GetSubscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscriptions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EAConnect__microsoft_dot_Server__pb2.GetSubscriptionsResp.SerializeToString,
            ),
            'SubscribeEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvent,
                    request_deserializer=EAConnect__microsoft_dot_Server__pb2.StreamMessage.FromString,
                    response_serializer=EAConnect__microsoft_dot_Server__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eax.services.ipc.GrpcServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.services.ipc.GrpcServer/CreateRequest',
            EAConnect__microsoft_dot_Server__pb2.Request.SerializeToString,
            EAConnect__microsoft_dot_Server__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eax.services.ipc.GrpcServer/GetSubscriptions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EAConnect__microsoft_dot_Server__pb2.GetSubscriptionsResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/eax.services.ipc.GrpcServer/SubscribeEvent',
            EAConnect__microsoft_dot_Server__pb2.StreamMessage.SerializeToString,
            EAConnect__microsoft_dot_Server__pb2.StreamMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
