# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x08\x65\x61\x64p.rtm\"\x8b\x02\n\x0eRichPresenceV1\x12\x0c\n\x04game\x18\x01 \x01(\t\x12&\n\x08platform\x18\x02 \x01(\x0e\x32\x14.eadp.rtm.PlatformV1\x12\x14\n\x0cgameModeType\x18\x03 \x01(\t\x12\x10\n\x08gameMode\x18\x04 \x01(\t\x12\x17\n\x0fgameSessionData\x18\x05 \x01(\t\x12\x34\n\x10richPresenceType\x18\x06 \x01(\x0e\x32\x1a.eadp.rtm.RichPresenceType\x12\x16\n\x0estartTimestamp\x18\x07 \x01(\t\x12\x14\n\x0c\x65ndTimestamp\x18\x08 \x01(\t\x12\x1e\n\x16\x63ustomRichPresenceData\x18\t \x01(\t\"-\n\x06Player\x12\x10\n\x08playerId\x18\x01 \x01(\t\x12\x11\n\tproductId\x18\x02 \x01(\t*\x93\x01\n\nPlatformV1\x12\x11\n\rNONE_PLATFORM\x10\x00\x12\x14\n\x10UNKNOWN_PLATFORM\x10\x01\x12\n\n\x06MOBILE\x10\x02\x12\x06\n\x02PC\x10\x03\x12\x07\n\x03WEB\x10\x04\x12\x0c\n\x08XBOXLIVE\x10\x05\x12\x07\n\x03PSN\x10\x06\x12\n\n\x06SWITCH\x10\x07\x12\t\n\x05STEAM\x10\x08\x12\x08\n\x04XBSK\x10\t\x12\x07\n\x03PS5\x10\n*8\n\x08UserType\x12\x12\n\x0eNONE_USER_TYPE\x10\x00\x12\x0b\n\x07PERSONA\x10\x01\x12\x0b\n\x07NUCLEUS\x10\x02*\x83\x01\n\x11\x42\x61sicPresenceType\x12\x11\n\rNONE_PRESENCE\x10\x00\x12\x14\n\x10UNKNOWN_PRESENCE\x10\x01\x12\x0b\n\x07OFFLINE\x10\x02\x12\n\n\x06ONLINE\x10\x03\x12\x07\n\x03\x44ND\x10\x04\x12\x08\n\x04\x41WAY\x10\x05\x12\r\n\tINVISIBLE\x10\x06\x12\n\n\x06\x43USTOM\x10\x07*`\n\x10RichPresenceType\x12\x16\n\x12NONE_RICH_PRESENCE\x10\x00\x12\x19\n\x15UNKNOWN_RICH_PRESENCE\x10\x01\x12\x07\n\x03LFG\x10\x02\x12\x10\n\x0c\x42ROADCASTING\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLATFORMV1']._serialized_start=344
  _globals['_PLATFORMV1']._serialized_end=491
  _globals['_USERTYPE']._serialized_start=493
  _globals['_USERTYPE']._serialized_end=549
  _globals['_BASICPRESENCETYPE']._serialized_start=552
  _globals['_BASICPRESENCETYPE']._serialized_end=683
  _globals['_RICHPRESENCETYPE']._serialized_start=685
  _globals['_RICHPRESENCETYPE']._serialized_end=781
  _globals['_RICHPRESENCEV1']._serialized_start=27
  _globals['_RICHPRESENCEV1']._serialized_end=294
  _globals['_PLAYER']._serialized_start=296
  _globals['_PLAYER']._serialized_end=341
# @@protoc_insertion_point(module_scope)
