# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requests.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\x12\x08\x65\x61\x64p.rtm\x1a\x0c\x63ommon.proto\"8\n\x13PresenceSubscribeV1\x12!\n\x07players\x18\x02 \x03(\x0b\x32\x10.eadp.rtm.Player\"\xab\x02\n\x0eLoginRequestV3\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\treconnect\x18\x02 \x01(\x08\x12\x11\n\theartbeat\x18\x03 \x01(\x08\x12$\n\x08userType\x18\x04 \x01(\x0e\x32\x12.eadp.rtm.UserType\x12\x11\n\tproductId\x18\x05 \x01(\t\x12&\n\x08platform\x18\x06 \x01(\x0e\x32\x14.eadp.rtm.PlatformV1\x12\x15\n\rclientVersion\x18\x07 \x01(\t\x12\x17\n\nsessionKey\x18\x08 \x01(\tH\x00\x88\x01\x01\x12&\n\x19\x66orceDisconnectSessionKey\x18\t \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_sessionKeyB\x1c\n\x1a_forceDisconnectSessionKey\"(\n\x12ReconnectRequestV1\x12\x12\n\nsessionKey\x18\x01 \x01(\t\"\xa7\x01\n\x10PresenceUpdateV1\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x36\n\x11\x62\x61sicPresenceType\x18\x02 \x01(\x0e\x32\x1b.eadp.rtm.BasicPresenceType\x12\x1b\n\x13userDefinedPresence\x18\x03 \x01(\t\x12.\n\x0crichPresence\x18\x04 \x01(\x0b\x32\x18.eadp.rtm.RichPresenceV1\"\r\n\x0bHeartbeatV1\"&\n\x10SessionCleanupV1\x12\x12\n\nsessionKey\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESENCESUBSCRIBEV1']._serialized_start=42
  _globals['_PRESENCESUBSCRIBEV1']._serialized_end=98
  _globals['_LOGINREQUESTV3']._serialized_start=101
  _globals['_LOGINREQUESTV3']._serialized_end=400
  _globals['_RECONNECTREQUESTV1']._serialized_start=402
  _globals['_RECONNECTREQUESTV1']._serialized_end=442
  _globals['_PRESENCEUPDATEV1']._serialized_start=445
  _globals['_PRESENCEUPDATEV1']._serialized_end=612
  _globals['_HEARTBEATV1']._serialized_start=614
  _globals['_HEARTBEATV1']._serialized_end=627
  _globals['_SESSIONCLEANUPV1']._serialized_start=629
  _globals['_SESSIONCLEANUPV1']._serialized_end=667
# @@protoc_insertion_point(module_scope)
