# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: responses.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'responses.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fresponses.proto\x12\x08\x65\x61\x64p.rtm\x1a\x0c\x63ommon.proto\"q\n\tSessionV1\x12\x12\n\nsessionKey\x18\x01 \x01(\t\x12&\n\x08platform\x18\x02 \x01(\x0e\x32\x14.eadp.rtm.PlatformV1\x12\x15\n\rclientVersion\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"U\n\x0fLoginV3Response\x12\x12\n\nsessionKey\x18\x01 \x01(\t\x12.\n\x11\x63onnectedSessions\x18\x02 \x03(\x0b\x32\x13.eadp.rtm.SessionV1\"I\n\tSuccessV1\x12\x34\n\x0floginV3Response\x18\x03 \x01(\x0b\x32\x19.eadp.rtm.LoginV3ResponseH\x00\x42\x06\n\x04\x62ody\"h\n\x07\x45rrorV1\x12\x11\n\terrorCode\x18\x01 \x01(\t\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12,\n\nloginError\x18\x07 \x01(\x0b\x32\x16.eadp.rtm.LoginErrorV1H\x00\x42\x06\n\x04\x62ody\">\n\x0cLoginErrorV1\x12.\n\x11\x63onnectedSessions\x18\x01 \x03(\x0b\x32\x13.eadp.rtm.SessionV1\"\xcf\x03\n\nPresenceV1\x12\x11\n\tpersonaId\x18\x01 \x01(\t\x12\x13\n\x06status\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x03 \x01(\tH\x01\x88\x01\x01\x12 \n\x06player\x18\x04 \x01(\x0b\x32\x10.eadp.rtm.Player\x12\x36\n\x11\x62\x61sicPresenceType\x18\x05 \x01(\x0e\x32\x1b.eadp.rtm.BasicPresenceType\x12 \n\x13userDefinedPresence\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x33\n\x0crichPresence\x18\x07 \x01(\x0b\x32\x18.eadp.rtm.RichPresenceV1H\x03\x88\x01\x01\x12\x17\n\nsessionKey\x18\x08 \x01(\tH\x04\x88\x01\x01\x12\x1a\n\rclientVersion\x18\t \x01(\tH\x05\x88\x01\x01\x12+\n\x08platform\x18\n \x01(\x0e\x32\x14.eadp.rtm.PlatformV1H\x06\x88\x01\x01\x42\t\n\x07_statusB\x0c\n\n_timestampB\x16\n\x14_userDefinedPresenceB\x0f\n\r_richPresenceB\r\n\x0b_sessionKeyB\x10\n\x0e_clientVersionB\x0b\n\t_platformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONV1']._serialized_start=43
  _globals['_SESSIONV1']._serialized_end=156
  _globals['_LOGINV3RESPONSE']._serialized_start=158
  _globals['_LOGINV3RESPONSE']._serialized_end=243
  _globals['_SUCCESSV1']._serialized_start=245
  _globals['_SUCCESSV1']._serialized_end=318
  _globals['_ERRORV1']._serialized_start=320
  _globals['_ERRORV1']._serialized_end=424
  _globals['_LOGINERRORV1']._serialized_start=426
  _globals['_LOGINERRORV1']._serialized_end=488
  _globals['_PRESENCEV1']._serialized_start=491
  _globals['_PRESENCEV1']._serialized_end=954
# @@protoc_insertion_point(module_scope)
