# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import requests_pb2 as requests__pb2
import responses_pb2 as responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trtm.proto\x12\x08\x65\x61\x64p.rtm\x1a\x0c\x63ommon.proto\x1a\x0erequests.proto\x1a\x0fresponses.proto\"6\n\rCommunication\x12%\n\x02v1\x18\x01 \x01(\x0b\x32\x19.eadp.rtm.CommunicationV1\"\xe6\x03\n\x0f\x43ommunicationV1\x12\x11\n\trequestId\x18\x01 \x01(\t\x12:\n\x11presenceSubscribe\x18\x02 \x01(\x0b\x32\x1d.eadp.rtm.PresenceSubscribeV1H\x00\x12\x34\n\x0epresenceUpdate\x18\x05 \x01(\x0b\x32\x1a.eadp.rtm.PresenceUpdateV1H\x00\x12(\n\x08presence\x18\x07 \x01(\x0b\x32\x14.eadp.rtm.PresenceV1H\x00\x12\"\n\x05\x65rror\x18\r \x01(\x0b\x32\x11.eadp.rtm.ErrorV1H\x00\x12\x38\n\x10reconnectRequest\x18\x0e \x01(\x0b\x32\x1c.eadp.rtm.ReconnectRequestV1H\x00\x12&\n\x07success\x18\x0f \x01(\x0b\x32\x13.eadp.rtm.SuccessV1H\x00\x12*\n\theartbeat\x18\x14 \x01(\x0b\x32\x15.eadp.rtm.HeartbeatV1H\x00\x12\x32\n\x0eloginRequestV3\x18. \x01(\x0b\x32\x18.eadp.rtm.LoginRequestV3H\x00\x12\x36\n\x10sessionCleanupV1\x18\x31 \x01(\x0b\x32\x1a.eadp.rtm.SessionCleanupV1H\x00\x42\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMUNICATION']._serialized_start=70
  _globals['_COMMUNICATION']._serialized_end=124
  _globals['_COMMUNICATIONV1']._serialized_start=127
  _globals['_COMMUNICATIONV1']._serialized_end=613
# @@protoc_insertion_point(module_scope)
